export const FETCH_IMAGE = "IMAGE_DETAIL/FETCH_IMAGE";

export const FETCH_IMAGE_SUCCEEDED = "IMAGE_DETAIL/FETCH_IMAGE/SUCCEEDED";

export const FETCH_IMAGE_FAILED = "IMAGE_DETAIL/FETCH_IMAGE/FAILED";

export const UPDATE_NOTES_SUCCEEDED = "IMAGE_DETAIL/IMAGE_INFO/NOTES_MODAL/UPDATE_IMAGE/SUCCEEDED";
