export const FETCH_IMAGES_LIST = "DASHBOARD/IMAGES_LIST/FETCH";
export const FETCH_IMAGES_LIST_SUCCEEDED = "DASHBOARD/IMAGES_LIST/FETCH/SUCCEEDED";

export const UPDATE_NOTES = "DASHBOARD/NOTES_MODAL/UPDATE_IMAGE_NOTES";
export const UPDATE_NOTES_SUCCEEDED = "DASHBOARD/NOTES_MODAL/UPDATE_IMAGE/SUCCEEDED";
export const HIDE_NOTES_SUCCEEDED_MESSAGE = "DASHBOARD/NOTES_MODAL/SUCCEEDED_MESSAGE/HIDE";

export const DELETE_IMAGE = "DASHBOARD/IMAGE/DELETE";
export const DELETE_IMAGE_SUCCEEDED = "DASHBOARD/IMAGE/DELETE/SUCCEEDED";
