export const FETCH_USER_IMAGES_LIST = "DASHBOARD/USER_IMAGES_LIST/FETCH";
export const FETCH_USER_IMAGES_LIST_SUCCEEDED = "DASHBOARD/USER_IMAGES_LIST/FETCH/SUCCEEDED";

export const TOGGLE_NOTES_MODAL = "DASHBOARD/NOTES_MODAL/TOGGLE";
export const UPDATE_MODAL_VALUE = "DASHBOARD/NOTES_MODAL/UPDATE_MODAL_VALUE";
export const UPDATE_NOTES = "DASHBOARD/NOTES_MODAL/UPDATE_IMAGE_NOTES";
export const UPDATE_NOTES_SUCCEEDED = "DASHBOARD/NOTES_MODAL/UPDATE_IMAGE_SUCCEEDED";

export const DELETE_IMAGE = "DASHBOARD/IMAGE/DELETE";
export const DELETE_IMAGE_SUCCEEDED = "DASHBOARD/IMAGE/DELETE/SUCCEEDED";
