export const FETCH_KERNEL_CONFIGURATOR_THEMES = "BUILDER/KERNEL_CONFIGURATION/KERNEL_CONFIGURATOR_THEMES/FETCH";

export const FETCH_KERNEL_CONFIGURATOR_THEMES_SUCCEEDED = "BUILDER/KERNEL_CONFIGURATION/KERNEL_CONFIGURATOR_THEMES/FETCH/SUCCEEDED";

export const INIT_NEW_KERNEL_CONFIGURATION = "BUILDER/KERNEL_CONFIGURATION/INIT_NEW_KERNEL_CONFIGURATION";

export const SET_KERNEL_CONFIGURATOR_THEME = "BUILDER/KERNEL_CONFIGURATION/SET_KERNEL_CONFIGURATOR_THEME";
