export const DELETE_IMAGE = "IMAGE/DELETE";

export const TOGGLE_NOTES_SUCCEEDED_MESSAGE = "IMAGE/NOTES_MODAL/TOGGLE_SUCCEEDED_MESSAGE";

export const UPDATE_NOTES = "IMAGE/NOTES_MODAL/UPDATE_IMAGE_NOTES";
