export const FETCH_CONFIGURATION_PARAMS = "BUILDER/CONFIGURATION/PARAMS/FETCH";

export const FETCH_CONFIGURATION_PARAMS_SUCCEEDED = "BUILDER/CONFIGURATION/PARAMS/FETCH/SUCCEEDED";

export const UPDATE_CONFIGURATION_PARAMS = "BUILDER/CONFIGURATION/PARAMS/UPDATE";

export const FETCH_TIME_ZONES_LIST = "BUILDER/CONFIGURATION/TIME_ZONES_LIST/FETCH";

export const FETCH_TIME_ZONES_LIST_SUCCEEDED = "BUILDER/CONFIGURATION/TIME_ZONES_LIST/FETCH/SUCCEEDED";

export const SET_FIELD_STATUS = "BUILDER/CONFIGURATION/SET_FIELD_STATUS";
