export const FETCH_DEVICE_LIST = "BUILDER/INITIALIZATION/DEVICE_LIST/FETCH";

export const SET_BUILD_TYPE = "BUILDER/INITIALIZATION/SET_BUILD_TYPE";

export const SET_BUILD_TYPE_LIST = "BUILDER/INITIALIZATION/SET_BUILD_TYPE_LIST";

export const SET_BUILD_UUID = "BUILDER/INITIALIZATION/SET_BUILD_UUID";

export const SET_DEVICE_SHORT_NAME = "BUILDER/INITIALIZATION/SET_DEVICE_SHORT_NAME";

export const SET_DEVICE_LIST = "BUILDER/INITIALIZATION/SET_DEVICE_LIST";

export const SET_DISTRO_SHORT_NAME = "BUILDER/INITIALIZATION/SET_DISTRO_SHORT_NAME";

export const SET_DISTRO_LIST = "BUILDER/INITIALIZATION/SET_DISTRO_LIST";

export const TOGGLE_CONTINUE_BUILD_MODAL = "BUILDER/INITIALIZATION/CONTINUE_BUILD_MODAL/TOGGLE";
