export const CONFIRM_EMAIL_REQUEST = "CONFIRM_EMAIL/REQUEST";

export const CONFIRM_EMAIL_REQUEST_FAILED = "CONFIRM_EMAIL/REQUEST/FAILED";

export const CONFIRM_EMAIL_REQUEST_SUCCEEDED = "CONFIRM_EMAIL/REQUEST/SUCCEEDED";
